# -*- mode: ruby -*-
# vi: set ft=ruby :

# CONFIGURATION

# mount directories from host to guest
shared_folders = {"#{Dir.home}/chef" => '/home/vagrant/chef'}

# VM with gui or headless
vm_gui = false
vm_memory = 1024
vm_cpus = 1

# ---- PLEASE, DO NO EDIT AFTER THIS LINE ----

# Vagrantfile API/syntax version
VAGRANTFILE_API_VERSION = '2'


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'chef-takeaway'
  # TODO -- UPDATE config.vm.box_url TO POINT TO CLOUD FILES/CDN
  # config.vm.box_url = 'http://10.16.11.60:8080/chef-takeaway.box'

  config.vm.hostname = 'chef-takeaway'

  config.vm.provider :virtualbox do |vb|
    vb.gui = vm_gui
    vb.memory = vm_memory
    vb.cpus = vm_cpus
  end

  # Uncomment below to enable NFS for sharing the host machine into the VM, e.g.:
  #
  #   config.vm.synced_folder ".", "/home/foo/share", id: "vagrant", :nfs => true, :mount_options => ['nolock,vers=3,udp']
  #
  shared_folders.each_with_index do |(host_folder, guest_folder), index|
    if File.directory?(host_folder)
      # config.vm.synced_folder host_folder.to_s, guest_folder.to_s, id: config.vm.hostname, nfs: true, mount_options: ['nolock,vers=3,udp'], create: true
      config.vm.synced_folder host_folder.to_s, guest_folder.to_s, id: config.vm.hostname, create: true
    else
      puts "Warning - host_folder #{host_folder.to_s} does not exist"
    end
  end

end
