---
- debug: msg='Install Chef stuff'

# Chef-df
- name: Download Chef-dk
  command: /usr/bin/wget https://opscode-omnibus-packages.s3.amazonaws.com/debian/6/x86_64/chefdk_0.4.0-1_amd64.deb -O /home/foo/download/chefdk_0.4.0-1_amd64.deb
  args:
    creates: /home/foo/download/chefdk_0.4.0-1_amd64.deb
  sudo: yes
  sudo_user: foo

- name: Install Chef-dk
  command: dpkg -i /home/foo/download/chefdk_0.4.0-1_amd64.deb

- name: Set up Chef-dk environment
  shell: chef shell-init bash >> ~/.bashrc
  args:
    chdir: /home/foo
  sudo: yes
  sudo_user: foo

# Vagrant - yeah, Vagrant inside Vagrant
- name: Download Vagrant
  shell: "wget -O /home/foo/download/{{ vagrant_pkg_file }} {{ vagrant_pkg_url }}"
  sudo: yes
  sudo_user: foo
  args:
    creates: /home/foo/download/{{ vagrant_pkg_file }}

- name: Install Vagrant
  shell: "dpkg -i /home/foo/download/{{ vagrant_pkg_file }}"

- name: Install Vagrant plugins
  shell: vagrant plugin install {{ item }}
  args:
    chdir: /home/foo
  sudo: yes
  sudo_user: foo
  with_items:
    - vagrant-proxyconf
    - vagrant-aws
    - vagrant-azure
    - vagrant-digitalocean
    - vagrant-google
    - vagrant-rackspace

# Docker
# see: https://docs.docker.com/installation/debian/
- name: Download Docker install script
  command: 'wget https://get.docker.com/ -O /tmp/get_docker_com'
  args:
    creates: /usr/bin/docker

- name: Install Docker
  command: 'sh /tmp/get_docker_com'
  args:
    creates: /usr/bin/docker

- name: Giving non-root access for foo user
  command: adduser foo docker

- name: Restart docker daemon to apply changes
  service: name=docker state=restarted

- name: Check foo user can run docker
  command: "docker ps"
  register: docker_ps
  failed_when: >
    docker_ps.rc != 0

# Kitchen
- name: Install test-kitchen drivers
  shell: eval "$(chef shell-init bash)" && gem install "{{ item }}"
  # args:
  #   chdir: /home/foo
  #   executable: /bin/bash
  sudo: yes
  sudo_user: foo
  with_items:
    - kitchen-docker
    - kitchen-rackspace

- name: Check Chef-dk is set up correctly
  command: "chef verify"
  register: chef_verify
  failed_when: >
    chef_verify.rc != 0
