---
- name: resolve dependencies, then install pip and pip packages
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - libffi-dev
    - python-dev

# install the latest pip version to solve:
#
#         ImportError: cannot import name IncompleteRead

- name: download pip installer
  get_url: url="https://bootstrap.pypa.io/get-pip.py" dest="/home/vagrant/download/get-pip.py"
  sudo: yes
  sudo_user: vagrant

- name: install pip
  command: python /home/vagrant/download/get-pip.py

- name: Install pip packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - requests
    - httpie
    - ipython
    - pyrax
    - python-heatclient
    - python-novaclient
    - python-openstackclient
    - python-openstacksdk
    - python-swiftclient
    - rackspace-auth-openstack
    - rackspace-novaclient
    - supernova
