#!/bin/bash

#set -e

# VM_NAME should match 'vm_name' in 'debian-7.8.0-amd64-cheftdd-virtualbox.json'
VM_NAME="chef-takeaway"
PACKER_TEMPLATE=debian-7.8.0-amd64-cheftdd-virtualbox.json

#export PACKER_LOG=1
rm ${VM_NAME}.box || true
packer build -only virtualbox-iso $PACKER_TEMPLATE
# vagrant box remove ${VM_NAME} || true
# vagrant box add ${VM_NAME} ${VM_NAME}.box
