---
driver:
  name: docker
  http_proxy: http://polipo:8123
  https_proxy: http://polipo:8123
  provision_command: env http_proxy=http://polipo:8123 bash -c 'curl -L
        http://www.chef.io/chef/install.sh | bash'

provisioner:
  name: chef_solo
  chef_omnibus_url: http://www.chef.io/chef/install.sh

platforms:
  - name: ubuntu

suites:
  - name: default
    run_list:
    attributes:
  - name: test1
    run_list:
    attributes:
