---
- name: create user's dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: vagrant
    group: vagrant
  with_items:
    - /home/vagrant/download
    - /home/vagrant/tmp
    - /vagrant/share
    - /vagrant/share/chef

- name: symlink share and chef dirs
  file: src={{ item.path }} dest={{ item.dest }} state=link
  with_items:
      - { path: '/vagrant/share', dest: '/home/vagrant/share' }

- name: copy user's files
  copy:
    src: home/vagrant/{{ item }}
    dest: /home/vagrant
    owner: vagrant
    group: vagrant
    mode: 0644
  with_items:
    - .bash_aliases
    - .bashrc

- name: create user's SSH key
  command: ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
  args:
    chdir: /home/vagrant
    creates: /home/vagrant/.ssh/id_rsa
  sudo: yes
  sudo_user: vagrant

- name:
  command: git clone https://github.com/magicmonty/bash-git-prompt.git .bash-git-prompt
  args:
    chdir: /home/vagrant
    creates: /home/vagrant/.bash-git-prompt
  sudo: yes
  sudo_user: vagrant
