---
- stat: path=/etc/init.d/virtualbox-ose-guest-utils
  register: virtualbox_ose_guest_utils

- service: name=virtualbox-ose-guest-utils state=stopped
  when: virtualbox_ose_guest_utils.stat.exists == True

- shell: "rmmod vboxguest"
  ignore_errors: True

- name: install virtualbox packages
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - virtualbox-ose-guest-x11
    - virtualbox-ose-guest-dkms
    - virtualbox-ose-guest-utils
    # Install dkms for dynamic compiles
    - dkms
    # If libdbus is not installed, virtualbox will not autostart
    - libdbus-1-3

- debug: msg="Install the VirtualBox guest additions"

- shell: "mount -o loop VBoxGuestAdditions.iso /mnt"

- shell: "yes|sh /mnt/VBoxLinuxAdditions.run"

- shell: "umount /mnt"

- shell: "rm -f VBoxLinuxAdditions.iso"

- name: start the newly build driver
  service: name=vboxadd state=started enabled=yes
