---
- include: packages.yml

- name: create Vagrant dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: vagrant
    group: vagrant
  with_items:
    - /home/vagrant/download
    - /home/vagrant/share
    - /home/vagrant/tmp
