---
- name: Install basic packages
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - curl
    - elinks
    - g++
    - git
    - iotop
    - mc
    - mtr
    - screen
