---
- debug: msg="current user {{ ansible_ssh_user }}"

- name: Enable Wheezy Backports repo
  apt_repository:
    repo='deb http://ftp.au.debian.org/debian wheezy-backports main' state=present
    update_cache: yes

- name: Enable Wheezy Backports source repo
  apt_repository:
    repo='deb-src http://ftp.au.debian.org/debian wheezy-backports main' state=present
    update_cache: yes

- name: Install basic packages
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - curl
    - elinks
    - g++
    - git
    - iotop
    - mc
    - mtr
    - screen
    - vim
  sudo: true
  sudo_user: root

- name: Update debian alternatives
  command: /usr/sbin/update-alternatives --set {{ item.name }} {{ item.path }}
  with_items:
    - name: editor
      path: /usr/bin/vim.basic
