---
- name: siso - Chef TDD Box
  hosts: servers
  roles:
    - base
    - users
    - chef
    - polipo
  vars:
    vagrant_pkg_file: vagrant_1.7.2_x86_64.deb
    vagrant_pkg_url: https://dl.bintray.com/mitchellh/vagrant/{{ vagrant_pkg_file }}
