---
- name: siso - Chef TDD Box 'chef-takeaway'
  hosts: all
  roles:
    - base
    - users
    - packer
    - chef
    - polipo
    - openstack
  vars:
    vagrant_pkg_file: vagrant_1.7.2_x86_64.deb
    vagrant_pkg_url: https://dl.bintray.com/mitchellh/vagrant/{{ vagrant_pkg_file }}
